# Generated by Django 5.2.11 on 2026-02-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orm_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetableRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('term', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.TextField(default='{}')),
            ],
            options={
                'db_table': 'exam_timetable_runs',
            },
        ),
    ]
