# Generated by Django 5.2.11 on 2026-02-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examtimetablerun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetablerun',
            name='term',
        ),
    ]
