# Generated by Django 5.2.11 on 2026-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_examtimetablerun_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmerequirement',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
