# Generated by Django 5.2.11 on 2026-02-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_is_online_to_programme_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_registered_credits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
