# Generated by Django 5.2.11 on 2026-02-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_current_registered_credits_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
