# Generated by Django 5.2.11 on 2026-02-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_is_external_to_course'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['student', 'status'], name='idx_sc_student_status'),
        ),
    ]
