# Generated by Django 5.2.11 on 2026-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dedup_studentcourse_and_prerequisite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.UniqueConstraint(fields=('program', 'course_code', 'prerequisite_course_code'), name='uq_prerequisites_program_course_prereq'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_student_courses_student_course'),
        ),
    ]
