# Generated by Django 5.2.11 on 2026-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_unique_constraints_sc_and_prereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmerequirement',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
