# Generated by Django 5.2.12 on 2026-04-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_max_capacity_to_programme_requirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("slots", models.JSONField(default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "time_slot_templates",
            },
        ),
        migrations.CreateModel(
            name="TimetableScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.TextField()),
                ("term", models.TextField()),
                ("name", models.TextField()),
                ("status", models.TextField(default="draft")),
                ("slot_config", models.JSONField(default=list)),
                ("created_by", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "timetable_scenarios",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("academic_year", "term", "name"),
                        name="ux_tt_scenario_year_term_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField()),
                ("nominal_term", models.IntegerField(blank=True, null=True)),
                ("board_type", models.TextField(default="standard")),
                ("program", models.TextField(blank=True, null=True)),
                ("target_size", models.IntegerField(default=0)),
                ("display_order", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="core.timetablescenario",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_boards",
            },
        ),
        migrations.CreateModel(
            name="BoardSectionVisibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_visibility",
                        to="core.termsection",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visible_sections",
                        to="core.deliveryboard",
                    ),
                ),
            ],
            options={
                "db_table": "board_section_visibility",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "term_section"), name="ux_bsv_board_section"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SectionPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.TextField()),
                ("start_time", models.TextField()),
                ("end_time", models.TextField()),
                ("room", models.TextField(blank=True, default="")),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="core.deliveryboard",
                    ),
                ),
                (
                    "term_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="core.termsection",
                    ),
                ),
            ],
            options={
                "db_table": "section_placements",
                "indexes": [
                    models.Index(fields=["board"], name="idx_sp_board"),
                    models.Index(fields=["term_section"], name="idx_sp_term_section"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "term_section", "day", "start_time"),
                        name="ux_placement_board_section_day_start",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="deliveryboard",
            index=models.Index(fields=["scenario"], name="idx_db_scenario"),
        ),
        migrations.AddConstraint(
            model_name="deliveryboard",
            constraint=models.UniqueConstraint(
                fields=("scenario", "label"), name="ux_delivery_board_scenario_label"
            ),
        ),
    ]
