# Generated by Django 5.2.12 on 2026-04-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_timetable_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardStudentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("link_type", models.TextField(default="primary")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="core.deliveryboard",
                    ),
                ),
            ],
            options={
                "db_table": "board_student_links",
                "indexes": [
                    models.Index(fields=["board"], name="idx_bsl_board"),
                    models.Index(
                        fields=["board", "link_type"], name="idx_bsl_board_type"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "student_id"), name="ux_bsl_board_student"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioSectionBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.TextField()),
                ("department", models.TextField(blank=True, default="")),
                ("credit_hours", models.IntegerField(default=0)),
                ("planned_sections", models.IntegerField(default=0)),
                ("max_per_section", models.IntegerField(default=40)),
                ("total_demand", models.IntegerField(default=0)),
                ("programme_term", models.IntegerField(blank=True, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_budgets",
                        to="core.timetablescenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_section_budgets",
                "indexes": [models.Index(fields=["scenario"], name="idx_ssb_scenario")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "course_code"),
                        name="ux_ssb_scenario_course",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioStudentMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("primary_term", models.IntegerField()),
                ("is_cross_term", models.BooleanField(default=False)),
                ("recommended_courses", models.JSONField(default=list)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_maps",
                        to="core.timetablescenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_student_maps",
                "indexes": [
                    models.Index(fields=["scenario"], name="idx_ssm_scenario"),
                    models.Index(
                        fields=["scenario", "primary_term"], name="idx_ssm_scenario_pt"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "student_id"),
                        name="ux_ssm_scenario_student",
                    )
                ],
            },
        ),
    ]
