# Generated by Django 5.2.12 on 2026-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_timetable_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetablescenario",
            name="lab_slot_config",
            field=models.JSONField(default=list),
        ),
    ]
