# Generated by Django 5.2.12 on 2026-04-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_timetable_lab_slot_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectiveCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.TextField()),
                ("course_name", models.TextField()),
                ("programme", models.TextField()),
                ("category", models.TextField(blank=True, default="")),
                ("credit_hours", models.IntegerField(default=3)),
                ("prerequisites_csv", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "elective_courses",
                "indexes": [
                    models.Index(fields=["programme"], name="idx_elective_programme")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("programme", "course_code"),
                        name="uq_elective_programme_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ElectiveTermMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.TextField()),
                ("term", models.IntegerField()),
                ("programme", models.TextField()),
                ("placeholder_code", models.TextField()),
                (
                    "elective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_mappings",
                        to="core.electivecourse",
                    ),
                ),
            ],
            options={
                "db_table": "elective_term_mappings",
                "indexes": [
                    models.Index(
                        fields=["academic_year", "term", "programme"],
                        name="idx_etm_year_term_prog",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "academic_year",
                            "term",
                            "programme",
                            "placeholder_code",
                            "elective",
                        ),
                        name="uq_elective_mapping",
                    )
                ],
            },
        ),
    ]
