# Generated by Django 5.2.12 on 2026-04-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_elective_catalogue"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="programmerequirement",
            index=models.Index(
                fields=["program", "programme_term"], name="idx_pr_program_term"
            ),
        ),
        migrations.AddIndex(
            model_name="sectionplacement",
            index=models.Index(
                fields=["board", "day", "start_time"], name="idx_sp_board_day_start"
            ),
        ),
        migrations.AddIndex(
            model_name="studentcourse",
            index=models.Index(
                fields=["course", "status"], name="idx_sc_course_status"
            ),
        ),
    ]
