# Generated by Django 5.2.12 on 2026-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.TextField(unique=True)),
                ("wing", models.TextField(blank=True, default="")),
                ("capacity", models.IntegerField(default=0)),
                ("department", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "rooms",
                "indexes": [
                    models.Index(fields=["department"], name="idx_room_department")
                ],
            },
        ),
    ]
