# Generated by Django 5.2.12 on 2026-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rooms_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.TextField(blank=True, default="lecture"),
        ),
    ]
