# Generated by Django 5.2.12 on 2026-04-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_room_building_floor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetablescenario",
            name="blocked_slots",
            field=models.JSONField(default=list),
        ),
    ]
