# Generated by Django 5.2.12 on 2026-04-12 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_blocked_slots"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="termsection",
            name="ux_term_sections_unique",
        ),
        migrations.AddField(
            model_name="termsection",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="term_sections",
                to="core.timetablescenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="termsection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scenario__isnull", False)),
                fields=("scenario", "course_key", "section"),
                name="ux_term_sections_scenario",
            ),
        ),
        migrations.AddConstraint(
            model_name="termsection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scenario__isnull", True)),
                fields=("course_key", "section"),
                name="ux_term_sections_global",
            ),
        ),
    ]
