# Generated by Django 5.2.12 on 2026-04-12 01:12
"""
Data migration: backfill TermSection.scenario for tw_auto sections.

For each tw_auto TermSection shared across multiple scenarios:
  1. Pick the first scenario as the "owner" (keeps the original row)
  2. For every other scenario, create a DUPLICATE TermSection row
  3. Clone all TermSectionMeeting rows from the original
  4. Repoint SectionPlacement FKs to the new per-scenario copy

Global sections (scraper_timetable, other, external) stay scenario=NULL.
"""

from django.db import migrations


def backfill_scenarios(apps, schema_editor):
    TermSection = apps.get_model("core", "TermSection")
    TermSectionMeeting = apps.get_model("core", "TermSectionMeeting")
    SectionPlacement = apps.get_model("core", "SectionPlacement")

    # Only process tw_auto sections (created by the timetable builder)
    tw_auto_sections = TermSection.objects.filter(source_tag="tw_auto")

    for ts in tw_auto_sections:
        # Find all scenarios that use this TermSection via SectionPlacement
        scenario_ids = list(
            SectionPlacement.objects.filter(term_section=ts)
            .values_list("board__scenario_id", flat=True)
            .distinct()
        )

        if not scenario_ids:
            # Orphan tw_auto section — no placements, leave as NULL
            continue

        if len(scenario_ids) == 1:
            # Used by exactly one scenario — just set the FK
            ts.scenario_id = scenario_ids[0]
            ts.save(update_fields=["scenario_id"])
            continue

        # Shared across multiple scenarios — need to duplicate.
        # First scenario keeps the original row.
        owner_scenario_id = scenario_ids[0]
        ts.scenario_id = owner_scenario_id
        ts.save(update_fields=["scenario_id"])

        # Get original meetings to clone
        original_meetings = list(
            TermSectionMeeting.objects.filter(term_section=ts).values(
                "day", "start_time", "end_time", "building",
                "floor_wing", "room", "instructor",
            )
        )

        # For each other scenario, create a duplicate TermSection + meetings
        for other_scenario_id in scenario_ids[1:]:
            new_ts = TermSection.objects.create(
                scenario_id=other_scenario_id,
                source_tag=ts.source_tag,
                course_name=ts.course_name,
                available_capacity=ts.available_capacity,
                registered_count=ts.registered_count,
                course_code=ts.course_code,
                course_number=ts.course_number,
                course_key=ts.course_key,
                section=ts.section,
                source_file=ts.source_file,
                created_at=ts.created_at,
                updated_at=ts.updated_at,
            )

            # Clone meetings
            for m in original_meetings:
                TermSectionMeeting.objects.create(
                    term_section=new_ts,
                    **m,
                )

            # Repoint SectionPlacement FKs for this scenario
            SectionPlacement.objects.filter(
                term_section=ts,
                board__scenario_id=other_scenario_id,
            ).update(term_section=new_ts)


def reverse_backfill(apps, schema_editor):
    """Reverse is not perfectly clean but safe: just clear scenario FKs."""
    TermSection = apps.get_model("core", "TermSection")
    TermSection.objects.filter(source_tag="tw_auto").update(scenario=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_scope_term_section_per_scenario"),
    ]

    operations = [
        migrations.RunPython(backfill_scenarios, reverse_backfill),
    ]
