# Generated by Django 5.2.12 on 2026-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_backfill_term_section_scenarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="section",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["section"], name="idx_room_section"),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("room_code", "section"), name="uniq_room_code_section"
            ),
        ),
    ]
