# Generated by Django 5.2.13 on 2026-04-21 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_room_section_alter_room_room_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerJob",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("optimise_current", "Optimise current"),
                            ("full_rebuild", "Full rebuild"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                (
                    "last_stage_seen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("greedy", "greedy"),
                            ("sa", "sa"),
                            ("cpsat", "cpsat"),
                            ("chain", "chain"),
                            ("rooming_repair", "rooming_repair"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("cancel_requested", models.BooleanField(default=False)),
                (
                    "request_signature",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planner_jobs",
                        to="core.deliveryboard",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planner_jobs",
                        to="core.timetablescenario",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planner_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "planner_jobs",
                "indexes": [
                    models.Index(
                        fields=["scenario", "status"], name="idx_pj_scenario_status"
                    ),
                    models.Index(
                        fields=["submitted_by", "-submitted_at"],
                        name="idx_pj_user_submitted",
                    ),
                ],
            },
        ),
    ]
