# Generated by Codex on 2026-05-05

from django.db import migrations, models


def _normalize_code(code):
    return str(code or "").replace("\u00a0", " ").strip().upper().replace(" ", "")


def backfill_course_names(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    ProgrammeRequirement = apps.get_model("core", "ProgrammeRequirement")
    db_alias = schema_editor.connection.alias

    course_names = {
        _normalize_code(code): description or ""
        for code, description in Course.objects.using(db_alias).values_list(
            "course_code", "description"
        )
    }

    requirements = ProgrammeRequirement.objects.using(db_alias).filter(course_name="")
    for requirement in requirements.iterator():
        course_name = course_names.get(_normalize_code(requirement.course_code), "")
        if course_name:
            requirement.course_name = course_name
            requirement.save(update_fields=["course_name"])


def reverse_backfill_course_names(apps, schema_editor):
    # Keep rollback non-destructive; reversing the migration drops the column.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_plannerjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmerequirement",
            name="course_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(backfill_course_names, reverse_backfill_course_names),
    ]
