# Generated by Django 5.2.13 on 2026-05-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_timetable_repair_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioStudentCourseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                ("course_key", models.TextField()),
                ("course_code", models.TextField()),
                ("course_name", models.TextField(blank=True, default="")),
                ("primary_term", models.IntegerField(blank=True, null=True)),
                ("is_cross_term", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("blocked", "Blocked"),
                            ("served", "Served"),
                            ("ignored", "Ignored"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("graduating", "Graduating"),
                            ("manual_approval", "Manual approval"),
                            ("special_case", "Special case"),
                        ],
                        default="normal",
                        max_length=32,
                    ),
                ),
                (
                    "reason_blocked",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("reason_detail", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(default="batch_recommender", max_length=64),
                ),
                ("source_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_course_requests",
                        to="core.timetablescenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_student_course_requests",
                "indexes": [
                    models.Index(
                        fields=["scenario", "course_key"],
                        name="idx_sscr_scenario_course",
                    ),
                    models.Index(
                        fields=["scenario", "student_id"],
                        name="idx_sscr_scenario_student",
                    ),
                    models.Index(
                        fields=["scenario", "status"], name="idx_sscr_scenario_status"
                    ),
                    models.Index(
                        fields=["scenario", "priority"],
                        name="idx_sscr_scenario_priority",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "student_id", "course_key"),
                        name="ux_sscr_scenario_student_course",
                    )
                ],
            },
        ),
    ]
