# Generated by Django 5.2.13 on 2026-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_repair_global_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannerjob",
            name="mode",
            field=models.CharField(
                choices=[
                    ("optimise_current", "Optimise current"),
                    ("full_rebuild", "Full rebuild"),
                    ("optimise_v2_full", "Optimise V2 (full rebuild)"),
                    ("optimise_v2_current", "Optimise V2 (current)"),
                ],
                max_length=32,
            ),
        ),
    ]
