# Generated by Django 5.2.13 on 2026-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_plannerjob_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerjob",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
