# Generated by Django 5.2.15 on 2026-06-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_plannerjob_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField()),
                ("normalised_name", models.TextField()),
                ("full_name_ar", models.TextField(blank=True, default="")),
                ("email", models.TextField(blank=True, default="")),
                ("employee_no", models.TextField(blank=True, default="")),
                ("department", models.TextField(blank=True, default="")),
                ("max_weekly_hours", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "instructors",
                "indexes": [
                    models.Index(fields=["department"], name="idx_instructors_dept"),
                    models.Index(fields=["is_active"], name="idx_instructors_active"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("normalised_name",),
                        name="ux_instructors_normalised_name",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("email__gt", "")),
                        fields=("email",),
                        name="ux_instructors_email_present",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SectionInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField(default="primary")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section_links",
                        to="core.instructor",
                    ),
                ),
                (
                    "term_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_links",
                        to="core.termsection",
                    ),
                ),
            ],
            options={
                "db_table": "section_instructors",
                "indexes": [
                    models.Index(fields=["term_section"], name="idx_si_term_section"),
                    models.Index(fields=["instructor"], name="idx_si_instructor"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term_section", "instructor"),
                        name="ux_section_instructor_unique",
                    )
                ],
            },
        ),
    ]
