# Generated by Django 5.2.15 on 2026-06-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_instructor_sectioninstructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetablescenario",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="timetablescenario",
            name="programs",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.TextField()),
                ("course_code", models.TextField()),
                (
                    "section",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("role", models.TextField(default="primary")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_links",
                        to="core.instructor",
                    ),
                ),
            ],
            options={
                "db_table": "course_instructors",
            },
        ),
        migrations.DeleteModel(
            name="SectionInstructor",
        ),
        migrations.AddIndex(
            model_name="courseinstructor",
            index=models.Index(
                fields=["program", "course_code", "section"], name="idx_ci_lookup"
            ),
        ),
        migrations.AddIndex(
            model_name="courseinstructor",
            index=models.Index(fields=["instructor"], name="idx_ci_instructor"),
        ),
        migrations.AddConstraint(
            model_name="courseinstructor",
            constraint=models.UniqueConstraint(
                fields=("program", "course_code", "section", "instructor"),
                name="ux_course_instructor_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseinstructor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("program", "course_code", "section"),
                name="ux_course_instructor_one_primary",
            ),
        ),
    ]
