# Generated by Django 5.2.16 on 2026-07-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_timetablescenario_gender_timetablescenario_programs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannerjob",
            name="mode",
            field=models.CharField(
                choices=[
                    ("optimise_current", "Optimise current"),
                    ("full_rebuild", "Full rebuild"),
                    ("optimise_v2_full", "Optimise V2 (full rebuild)"),
                    ("optimise_v2_current", "Optimise V2 (current)"),
                    ("scheduler_build", "New scheduler engine"),
                ],
                max_length=32,
            ),
        ),
    ]
