# Generated by Django 5.2.16 on 2026-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_plannerjob_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannerjob",
            name="last_stage_seen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("greedy", "greedy"),
                    ("sa", "sa"),
                    ("cpsat", "cpsat"),
                    ("chain", "chain"),
                    ("rooming_repair", "rooming_repair"),
                    ("snapshot", "snapshot"),
                    ("solve", "solve"),
                    ("rooming", "rooming"),
                    ("persist", "persist"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
