# Generated by Django 5.2.16 on 2026-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_plannerjob_last_stage_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLoginOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField(db_index=True)),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("consumed", models.BooleanField(default=False)),
                ("request_ip", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "db_table": "core_student_login_otp",
                "indexes": [
                    models.Index(
                        fields=["student_id", "consumed"],
                        name="ix_otp_student_consumed",
                    )
                ],
            },
        ),
    ]
