# Generated by Django 5.2.16 on 2026-07-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_studentloginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscope",
            name="student_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
