# Generated by Django 5.2.16 on 2026-08-01 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_userscope_student_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.IntegerField(db_index=True)),
                ("title", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "advisor_conversations",
                "ordering": ["-last_message_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student_id", "-last_message_at"],
                        name="idx_adv_conv_student",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AdvisorMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("ASSISTANT", "Assistant")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "answer_mode",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "grounding_state",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "final_disposition",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "model_revision",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AGENT", "Agent loop"),
                            ("SEEDED_FALLBACK", "Seeded fallback"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.advisorconversation",
                    ),
                ),
            ],
            options={
                "db_table": "advisor_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField(db_index=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("HELPFUL", "Helpful"),
                            ("NOT_HELPFUL", "Not helpful"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.advisormessage",
                    ),
                ),
            ],
            options={
                "db_table": "advisor_feedback",
            },
        ),
        migrations.CreateModel(
            name="AdvisorMessageCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=120)),
                ("document_title", models.TextField(blank=True, default="")),
                ("edition", models.CharField(blank=True, default="", max_length=60)),
                ("page", models.CharField(blank=True, default="", max_length=40)),
                (
                    "effective_from",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "effective_to",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "authority_status",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("VALID", "Valid"), ("INVALID", "Invalid")],
                        default="VALID",
                        max_length=16,
                    ),
                ),
                (
                    "source_version_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations",
                        to="core.advisormessage",
                    ),
                ),
            ],
            options={
                "db_table": "advisor_message_citations",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="advisormessage",
            index=models.Index(
                fields=["conversation", "created_at"], name="idx_adv_msg_conv"
            ),
        ),
        migrations.AddConstraint(
            model_name="advisormessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("conversation", "idempotency_key"),
                name="uq_adv_msg_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="advisorfeedback",
            index=models.Index(fields=["rating"], name="idx_adv_fb_rating"),
        ),
        migrations.AddConstraint(
            model_name="advisorfeedback",
            constraint=models.UniqueConstraint(
                fields=("message", "student_id"), name="uq_adv_feedback_message_student"
            ),
        ),
        migrations.AddIndex(
            model_name="advisormessagecitation",
            index=models.Index(fields=["message"], name="idx_adv_cit_message"),
        ),
        migrations.AddIndex(
            model_name="advisormessagecitation",
            index=models.Index(fields=["policy_id"], name="idx_adv_cit_policy"),
        ),
    ]
