# Generated by Django 5.2.16 on 2026-08-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_advisorconversation_advisormessage_advisorfeedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisormessage",
            name="request_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="advisormessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("ABSTAINED", "Abstained"),
                    ("ESCALATED", "Escalated"),
                ],
                default="COMPLETED",
                max_length=16,
            ),
        ),
    ]
