# Generated by Django 5.2.16 on 2026-08-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_advisormessage_request_hash_advisormessage_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advisorconversation",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("last_message_at"), descending=True, nulls_last=True
                    ),
                    "-created_at",
                ]
            },
        ),
    ]
