# Generated by Django 5.2.16 on 2026-08-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_advisor_conversation_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisormessage",
            name="generation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advisormessage",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="core.advisormessage",
            ),
        ),
    ]
