# Generated by Django 5.2.16 on 2026-08-02 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_advisor_message_turn_pairing"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorEscalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.IntegerField(db_index=True)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            (
                                "PROHIBITED_FOR_DECISION",
                                "The regulation forbids deciding this case automatically",
                            ),
                            (
                                "MISSING_INFORMATION",
                                "Required information was unavailable",
                            ),
                            (
                                "NO_GROUNDED_ANSWER",
                                "No approved policy covered the question",
                            ),
                            (
                                "STUDENT_REQUESTED",
                                "The student asked for a human adviser",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("student_note", models.TextField(blank=True, default="")),
                ("generated_summary", models.TextField(blank=True, default="")),
                ("evidence_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("NEEDS_INFORMATION", "Needs information"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                (
                    "assigned_adviser_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("adviser_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="core.advisorconversation",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="core.advisormessage",
                    ),
                ),
            ],
            options={
                "db_table": "advisor_escalations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student_id", "-created_at"], name="idx_adv_esc_student"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="idx_adv_esc_status"
                    ),
                    models.Index(
                        fields=["assigned_adviser_id"], name="idx_adv_esc_adviser"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ("RESOLVED", "CLOSED")), _negated=True
                        ),
                        fields=("source_message",),
                        name="uq_adv_esc_one_open_per_message",
                    )
                ],
            },
        ),
    ]
