# Generated by Django 5.2.16 on 2026-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_advisor_escalation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "rate_limit_buckets",
                "indexes": [
                    models.Index(fields=["window_start"], name="idx_ratelimit_window")
                ],
            },
        ),
    ]
