# Generated by Django 5.2.16 on 2026-08-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_rate_limit_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratelimitbucket",
            name="previous_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
