# Generated by Django 5.2.16 on 2026-08-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_rate_limit_previous_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisormessage",
            name="missing_information",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="advisormessage",
            name="outcome_schema_version",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="advisormessage",
            name="reason_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="advisormessage",
            name="final_disposition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASS", "Answered"),
                    ("ABSTAIN", "Declined to answer"),
                    ("ESCALATE", "Sent to a human adviser"),
                    ("FAILED", "Could not be produced"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
