# Generated by Django 5.2.16 on 2026-08-02 06:49

from django.db import migrations, models

#: The values this table used before the vocabulary was shared with the assistant
#: turn. None of them maps safely onto the new set: MISSING_INFORMATION might be a
#: student fact, a policy, a procedure or a calendar window, and NO_GROUNDED_ANSWER
#: might be POLICY_NOT_FOUND, POLICY_UNAVAILABLE, PROCEDURE_NOT_DOCUMENTED, or
#: records retrieved of which none governs. Guessing would invent a more specific
#: reason than anyone recorded, and an adviser queue would then sort on the guess.
_RETIRED = ("MISSING_INFORMATION", "NO_GROUNDED_ANSWER")


def refuse_to_guess_at_old_reasons(apps, schema_editor):
    """The model shipped unused, so the expected count is zero.

    If that assumption is wrong the rows are real cases, and they need a person to
    say what each one meant. Failing loudly here is the only honest option.
    """
    Escalation = apps.get_model("core", "AdvisorEscalation")
    stranded = Escalation.objects.filter(reason_code__in=_RETIRED)
    if stranded.exists():
        counts = {
            value: stranded.filter(reason_code=value).count()
            for value in _RETIRED
            if stranded.filter(reason_code=value).exists()
        }
        raise RuntimeError(
            "AdvisorEscalation rows still carry retired reason codes and cannot be "
            f"mapped automatically: {counts}. Re-classify them by hand — none of the "
            "old values has a single correct successor."
        )


def noop(apps, schema_editor):
    """Nothing to undo: the guard writes no data."""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_advisor_typed_outcome"),
    ]

    operations = [
        migrations.RunPython(refuse_to_guess_at_old_reasons, noop),
        migrations.AlterField(
            model_name="advisorescalation",
            name="reason_code",
            field=models.CharField(
                choices=[
                    (
                        "PROHIBITED_FOR_DECISION",
                        "The regulation reserves this decision to a person",
                    ),
                    ("POLICY_NOT_FOUND", "No approved policy governs the question"),
                    ("POLICY_UNAVAILABLE", "The policy store could not be consulted"),
                    ("STUDENT_DATA_MISSING", "Required student facts were unavailable"),
                    ("PROCEDURE_NOT_DOCUMENTED", "The procedure is not written down"),
                    (
                        "CONFLICTING_AUTHORITIES",
                        "Sources disagree and a person must choose",
                    ),
                    ("JUDGE_REJECTED", "The answer did not survive review"),
                    ("MODEL_UNAVAILABLE", "No answer could be produced"),
                    ("STUDENT_REQUESTED", "The student asked for a human adviser"),
                ],
                max_length=32,
            ),
        ),
    ]
