# Generated by Django 5.2.16 on 2026-08-02 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_advisor_case_reference_and_resolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorEscalationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OPENED", "Opened by the student"),
                            ("VIEWED", "Opened by an adviser"),
                            ("ASSIGNED", "Assigned"),
                            ("STATUS_CHANGED", "Status changed"),
                            ("NOTE_ADDED", "Internal note added"),
                            ("RESPONSE_RECORDED", "Reply to the student recorded"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisor_escalation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.advisorescalation",
                    ),
                ),
            ],
            options={
                "db_table": "advisor_escalation_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["escalation", "created_at"], name="idx_adv_evt_case"
                    )
                ],
            },
        ),
    ]
