# Generated by Django 5.2.16 on 2026-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_advisor_escalation_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advisormessage",
            options={"ordering": ["sequence", "created_at"]},
        ),
        migrations.AddField(
            model_name="advisormessage",
            name="sequence",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
