# Generated by Django 5.2.16 on 2026-08-02 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_advisor_message_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.IntegerField(db_index=True)),
                ("course_codes", models.JSONField(blank=True, default=list)),
                ("fixed_sections", models.JSONField(blank=True, default=dict)),
                ("keep_current_sections", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planner_drafts",
                        to="core.advisormessage",
                    ),
                ),
            ],
            options={
                "db_table": "planner_drafts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student_id", "-created_at"], name="idx_draft_student"
                    ),
                    models.Index(fields=["expires_at"], name="idx_draft_expiry"),
                ],
            },
        ),
    ]
