# Generated by Django 5.2.16 on 2026-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_planner_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerdraft",
            name="alternatives",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="generated_inputs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="generation_schema_version",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="rebuild_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="rebuild_token_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="selected_alternative",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
