# Generated by Django 5.2.16 on 2026-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_planner_draft_generation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plannerdraft",
            name="rebuild_token",
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="rebuild_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="rebuild_token_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
