# Generated by Django 5.2.16 on 2026-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_planner_draft_rebuild_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerdraft",
            name="academic_year",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="plannerdraft",
            name="term",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
    ]
