# Generated by Django 5.2.16 on 2026-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_planner_draft_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerdraft",
            name="generated_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
