# Generated by Django 5.2.16 on 2026-08-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_planner_draft_generated_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorescalation",
            name="reason_code",
            field=models.CharField(
                choices=[
                    (
                        "PROHIBITED_FOR_DECISION",
                        "The regulation reserves this decision to a person",
                    ),
                    ("POLICY_NOT_FOUND", "No approved policy governs the question"),
                    ("POLICY_UNAVAILABLE", "The policy store could not be consulted"),
                    ("STUDENT_DATA_MISSING", "Required student facts were unavailable"),
                    ("PROCEDURE_NOT_DOCUMENTED", "The procedure is not written down"),
                    (
                        "CONFLICTING_AUTHORITIES",
                        "Sources disagree and a person must choose",
                    ),
                    ("JUDGE_REJECTED", "The answer did not survive review"),
                    ("MODEL_UNAVAILABLE", "No answer could be produced"),
                    ("STUDENT_REQUESTED", "The student asked for a human adviser"),
                    (
                        "OUTPUT_NOT_GROUNDED",
                        "The answer named identifiers the evidence does not support",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
