# Generated by Django 5.2.16 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_advisor_output_not_grounded_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisormessage",
            name="presentation",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
