# Generated by Django 5.2.15 on 2026-08-09 06:14

from typing import Any

import django.db.models.deletion
from django.db import migrations, models


def backfill_observed_program_memberships(apps: Any, schema_editor: Any) -> None:
    Student = apps.get_model("core", "Student")
    StudentTermSection = apps.get_model("core", "StudentTermSection")
    TermSectionProgram = apps.get_model("core", "TermSectionProgram")
    database = schema_editor.connection.alias

    student_programs: dict[int, str] = {}
    for student_id, raw_program in Student.objects.using(database).values_list(
        "student_id",
        "program",
    ):
        program = str(raw_program or "").strip().upper()
        if program and len(program) <= 32:
            student_programs[int(student_id)] = program

    memberships: set[tuple[int, str]] = set()
    registrations = (
        StudentTermSection.objects.using(database)
        .filter(term_section__scenario__isnull=True)
        .values_list("term_section_id", "student_id")
        .iterator(chunk_size=2_000)
    )
    for term_section_id, student_id in registrations:
        program = student_programs.get(int(student_id), "")
        if program:
            memberships.add((int(term_section_id), program))

    TermSectionProgram.objects.using(database).bulk_create(
        [
            TermSectionProgram(
                term_section_id=term_section_id,
                program=program,
                assignment_source="observed",
            )
            for term_section_id, program in sorted(memberships)
        ],
        ignore_conflicts=True,
        batch_size=1_000,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_advisor_message_presentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermSectionProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=32)),
                (
                    "assignment_source",
                    models.CharField(default="observed", max_length=24),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "term_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_links",
                        to="core.termsection",
                    ),
                ),
            ],
            options={
                "db_table": "term_section_programs",
                "indexes": [
                    models.Index(
                        fields=["program", "term_section"],
                        name="idx_tsp_program_section",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term_section", "program"),
                        name="uq_term_section_program",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("program", ""), _negated=True),
                        name="ck_tsp_program_nonempty",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_observed_program_memberships,
            migrations.RunPython.noop,
        ),
    ]
