# Generated by Django 5.2.16 on 2026-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_termsectionprogram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcourse",
            name="status",
            field=models.TextField(
                choices=[
                    ("passed", "Passed"),
                    ("studying", "Studying"),
                    ("failed", "Failed"),
                    ("not_taken", "Not taken"),
                ],
                default="not_taken",
            ),
        ),
    ]
