# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_student_course_failed_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studenttermsection",
            name="ux_student_term_sections_unique",
        ),
        migrations.AddConstraint(
            model_name="studenttermsection",
            constraint=models.UniqueConstraint(
                fields=("student_id", "academic_year", "term", "term_section"),
                name="ux_sts_student_term_section",
            ),
        ),
    ]
