# Generated by Django 5.2.16 on 2026-08-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_advisor_message_generation_profile"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studenttermsection",
            name="ux_sts_student_term_section",
        ),
        migrations.AddIndex(
            model_name="studenttermsection",
            index=models.Index(
                fields=["student_id", "academic_year", "term"],
                name="ix_sts_student_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttermsection",
            constraint=models.UniqueConstraint(
                fields=(
                    "student_id",
                    "academic_year",
                    "term",
                    "term_section",
                    "source",
                ),
                name="ux_sts_student_term_section_source",
            ),
        ),
    ]
