# Generated by Django 5.2.16 on 2026-08-21

from django.db import migrations, models


def mark_historical_delivery_state(apps, schema_editor):
    """Old rows predate delivery receipts, so do not claim they were accepted."""

    StudentLoginOTP = apps.get_model("core", "StudentLoginOTP")
    StudentLoginOTP.objects.using(schema_editor.connection.alias).update(
        delivery_status="skipped"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_allow_expected_and_registered_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentloginotp",
            name="delivery_channel",
            field=models.CharField(
                choices=[("smtp", "SMTP"), ("sendgrid", "Twilio SendGrid")],
                db_default="smtp",
                default="smtp",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="studentloginotp",
            name="delivery_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentloginotp",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("skipped", "Historical / unknown"),
                ],
                db_default="skipped",
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="studentloginotp",
            name="provider_message_id",
            field=models.CharField(blank=True, db_default="", default="", max_length=255),
        ),
        migrations.RunPython(mark_historical_delivery_state, migrations.RunPython.noop),
    ]
