# Generated by Django 5.2.16 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_studentloginotp_delivery_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisormessage",
            name="evidence_audit",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
