# Generated by Django 5.2.17 on 2026-09-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_repoint_ds2_math471_calculus_prerequisite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_key", models.TextField()),
                ("section", models.TextField()),
                ("role", models.TextField(default="primary")),
                ("source", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section_links",
                        to="core.instructor",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_instructors",
                        to="core.timetablescenario",
                    ),
                ),
            ],
            options={
                "db_table": "section_instructors",
                "indexes": [
                    models.Index(
                        fields=["course_key", "section"], name="idx_si_lookup"
                    ),
                    models.Index(fields=["instructor"], name="idx_si_instructor"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scenario__isnull", False)),
                        fields=("scenario", "course_key", "section", "instructor"),
                        name="ux_section_instructor_scenario",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scenario__isnull", True)),
                        fields=("course_key", "section", "instructor"),
                        name="ux_section_instructor_global",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("role", "primary"), ("scenario__isnull", False)
                        ),
                        fields=("scenario", "course_key", "section"),
                        name="ux_section_instructor_one_primary_scenario",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("role", "primary"), ("scenario__isnull", True)
                        ),
                        fields=("course_key", "section"),
                        name="ux_section_instructor_one_primary_global",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("course_key", ""), _negated=True),
                        name="ck_si_course_key_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("section", ""), _negated=True),
                        name="ck_si_section_nonempty",
                    ),
                ],
            },
        ),
    ]
