# Generated by Django 5.2.17 on 2026-09-21 10:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_section_instructor"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sectioninstructor",
            name="ck_si_course_key_nonempty",
        ),
        migrations.RemoveConstraint(
            model_name="sectioninstructor",
            name="ck_si_section_nonempty",
        ),
        migrations.AlterField(
            model_name="sectioninstructor",
            name="role",
            field=models.TextField(
                choices=[
                    ("primary", "Primary"),
                    ("co", "Co-instructor"),
                    ("lab", "Lab"),
                ],
                default="primary",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectioninstructor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "course_key",
                        django.db.models.functions.text.Upper(
                            django.db.models.functions.text.Trim(models.F("course_key"))
                        ),
                    ),
                    models.Q(("course_key", ""), _negated=True),
                ),
                name="ck_si_course_key_normalised",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectioninstructor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "section",
                        django.db.models.functions.text.Upper(
                            django.db.models.functions.text.Trim(models.F("section"))
                        ),
                    ),
                    models.Q(("section", ""), _negated=True),
                ),
                name="ck_si_section_normalised",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectioninstructor",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("primary", "co", "lab"))),
                name="ck_si_role_valid",
            ),
        ),
    ]
