# Generated by Django 5.2.17 on 2026-09-23 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_elective_mapping_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamTimetableJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("build", "Build"),
                            ("optimize_loaded", "Optimize current timetable"),
                            ("minimum_change_repair", "Fix with fewest moves"),
                            ("save_loaded_changes", "Save changes"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "lane",
                    models.CharField(default="exam", editable=False, max_length=16),
                ),
                (
                    "client_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("editor_revision", models.IntegerField(default=0)),
                ("request_payload", models.JSONField(default=dict)),
                ("progress_json", models.JSONField(default=dict)),
                ("cancel_requested", models.BooleanField(default=False)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_json", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=40)),
                ("worker", models.CharField(blank=True, default="", max_length=128)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="core.examtimetablerun",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_timetable_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exam_timetable_jobs",
                "indexes": [
                    models.Index(
                        fields=["status", "heartbeat_at"],
                        name="exam_job_status_heartbeat",
                    ),
                    models.Index(
                        fields=["submitted_by", "-submitted_at"],
                        name="exam_job_user_recent",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("queued", "running"))),
                        fields=("lane",),
                        name="exam_job_one_active",
                    )
                ],
            },
        ),
    ]
