# Generated by Django 5.2.17 on 2026-09-28 06:13

from django.db import migrations, models
from django.db.models import F


def copy_capacity(apps, schema_editor):
    """Start every room's exam capacity at its capacity."""
    Room = apps.get_model("core", "Room")
    Room.objects.using(schema_editor.connection.alias).update(exam_capacity=F("capacity"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_exam_job_panel_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="exam_capacity",
            field=models.IntegerField(default=0),
        ),
        # Reversing drops the column, so there is nothing to undo here.
        migrations.RunPython(copy_capacity, migrations.RunPython.noop),
    ]
