# Generated by Django 5.2.17 on 2026-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_room_exam_capacity_follows_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examtimetablejob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("build", "Build"),
                    ("optimize_loaded", "Optimize current timetable"),
                    ("minimum_change_repair", "Fix with fewest moves"),
                    ("save_loaded_changes", "Save changes"),
                    ("add_courses", "Add courses"),
                ],
                max_length=32,
            ),
        ),
    ]
