"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from project root .env if present
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.getenv("DJANGO_SECRET_KEY", "")
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    # Allow insecure fallback ONLY in local development (DEBUG=True)
    SECRET_KEY = "django-insecure-dev-only-change-me"  # noqa: S105
else:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY environment variable is required when DEBUG is False."
    )

ALLOWED_HOSTS: list[str] = [
    h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "whatsapp_gateway",
    # New timetabling subsystem. Deliberately isolated from core's timetable
    # engine: shares no code, no tables and no state, so it cannot regress the
    # timetable in production use today. See docs/SCHEDULER-BLUEPRINT.md.
    "scheduler",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Must be after SessionMiddleware and before CommonMiddleware.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# In production, set DATABASE_URL (e.g. postgres://user:pass@host:5432/dbname).
# Locally falls back to SQLite.

_database_url = os.getenv("DATABASE_URL")
if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
            "OPTIONS": {
                "timeout": 30,
            },
        }
    }

# Cache backend for rate limiting and login throttling
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "advisor-cache",
    }
}

# Legacy parity DB used by migrated advisor logic (can be overridden via env var)
DB_PATH = os.getenv("ADVISOR_DB_PATH", str(BASE_DIR / "db.sqlite3"))

# Local-only OpenAI-compatible LLM endpoint.  LM Studio defaults to this port.
LOCAL_LLM_BASE_URL = os.getenv("LOCAL_LLM_BASE_URL", "http://localhost:1234/v1")
LOCAL_LLM_MODEL = os.getenv("LOCAL_LLM_MODEL", "")
LOCAL_LLM_TIMEOUT_SECONDS = float(os.getenv("LOCAL_LLM_TIMEOUT_SECONDS", "120"))
LOCAL_LLM_MAX_TOKENS = int(os.getenv("LOCAL_LLM_MAX_TOKENS", "1400"))
LOCAL_LLM_ALLOW_REMOTE = os.getenv("LOCAL_LLM_ALLOW_REMOTE", "false").lower() == "true"

# ── which LLM backend the adviser speaks to ──────────────────────
# "local"   — the OpenAI-compatible server above (LM Studio &c.)
# "alibaba" — Alibaba Cloud Model Studio, OpenAI-compatible endpoint
#
# Returning to local is this one variable and a restart. There is no prompt fork,
# no tool-registry fork and no branch to change. An unknown value fails at
# configuration time rather than silently falling back, because "the backend I
# did not intend" is worse than "the adviser refused to start".
LLM_BACKEND = os.getenv("LLM_BACKEND", "local").strip().lower()

# Alibaba Cloud Model Studio. Empty by default: the adviser is local until
# somebody deliberately configures otherwise, and every one of these is REQUIRED
# before the alibaba backend will start. The model is never discovered from the
# workspace — a silent choice of model is a silent choice of price.
ALIBABA_LLM_BASE_URL = os.getenv("ALIBABA_LLM_BASE_URL", "")
ALIBABA_LLM_API_KEY = os.getenv("ALIBABA_LLM_API_KEY", "")
ALIBABA_LLM_MODEL = os.getenv("ALIBABA_LLM_MODEL", "")
# Non-thinking for the first provider comparison: the local model has already
# spent whole tool turns on hidden reasoning, and comparing two providers while
# also changing reasoning mode measures neither.
ALIBABA_LLM_ENABLE_THINKING = os.getenv("ALIBABA_LLM_ENABLE_THINKING", "false").lower() == "true"
ALIBABA_LLM_TIMEOUT_SECONDS = float(os.getenv("ALIBABA_LLM_TIMEOUT_SECONDS", "75"))
ALIBABA_LLM_MAX_TOKENS = int(os.getenv("ALIBABA_LLM_MAX_TOKENS", "3000"))
ALIBABA_LLM_MAX_RETRIES = int(os.getenv("ALIBABA_LLM_MAX_RETRIES", "2"))

# The evaluation JUDGE is configured separately and defaults to local, ON PURPOSE.
# Judging Alibaba-generated answers with Alibaba confounds the comparison: a
# provider marking its own homework is not a measurement.
EVAL_JUDGE_LLM_BACKEND = os.getenv("EVAL_JUDGE_LLM_BACKEND", "local").strip().lower()

# Virtual advisor agent loop (native LLM tool calling over the capability
# registry). Env-overridable kill-switch: set to "false" to revert to the
# single-shot regex-planned behaviour with no redeploy.
VIRTUAL_ADVISOR_AGENT_LOOP_ENABLED = (
    os.getenv("VIRTUAL_ADVISOR_AGENT_LOOP_ENABLED", "true").lower() == "true"
)
VIRTUAL_ADVISOR_MAX_TOOL_ITERATIONS = int(os.getenv("VIRTUAL_ADVISOR_MAX_TOOL_ITERATIONS", "5"))
VIRTUAL_ADVISOR_MAX_TOOL_CALLS = int(os.getenv("VIRTUAL_ADVISOR_MAX_TOOL_CALLS", "12"))
# Token budget for tool-enabled turns. Thinking models (Qwen reasoning
# variants) burn output tokens on hidden reasoning before tool calls or
# answers, so loop turns need more headroom than plain chat turns.
VIRTUAL_ADVISOR_LOOP_MAX_TOKENS = int(os.getenv("VIRTUAL_ADVISOR_LOOP_MAX_TOKENS", "3000"))
# Per-turn HTTP timeout for tool-enabled turns. Thinking models can stall
# a tool turn for the full LOCAL_LLM_TIMEOUT_SECONDS; a shorter per-turn
# limit hands control to the fast no-tools rescue path sooner.
VIRTUAL_ADVISOR_TOOL_TURN_TIMEOUT_SECONDS = float(
    os.getenv("VIRTUAL_ADVISOR_TOOL_TURN_TIMEOUT_SECONDS", "75")
)

# WhatsApp Advisor Gateway. Keep credentials out of the repository.
WHATSAPP_CLOUD_API_VERSION = os.getenv("WHATSAPP_CLOUD_API_VERSION", "v23.0")
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN", "")
WHATSAPP_APP_SECRET = os.getenv("WHATSAPP_APP_SECRET", "")
WHATSAPP_REQUIRE_SIGNATURE = (
    os.getenv("WHATSAPP_REQUIRE_SIGNATURE", "false" if DEBUG else "true").lower() == "true"
)
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_STUDENT_EMAIL_DOMAIN = os.getenv("WHATSAPP_STUDENT_EMAIL_DOMAIN", "")
WHATSAPP_OTP_TTL_SECONDS = int(os.getenv("WHATSAPP_OTP_TTL_SECONDS", "300"))
WHATSAPP_OTP_MAX_ATTEMPTS = int(os.getenv("WHATSAPP_OTP_MAX_ATTEMPTS", "5"))
WHATSAPP_ALLOW_SUPER_ADMIN = os.getenv("WHATSAPP_ALLOW_SUPER_ADMIN", "false").lower() == "true"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "advisor-bot@localhost")

# Email / SMTP (Gmail app-password). Credentials come from .env, never the repo.
# Falls back to the console backend when no password is set, so dev works without
# credentials and real mail starts the moment EMAIL_HOST_PASSWORD is filled in.
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "20"))
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST_PASSWORD
    else "django.core.mail.backends.console.EmailBackend",
)
# Student OTP-login email domain (deterministic {student_id}@domain).
STUDENT_EMAIL_DOMAIN = os.getenv("STUDENT_EMAIL_DOMAIN", "taibahu.edu.sa")
STUDENT_OTP_TTL_SECONDS = int(os.getenv("STUDENT_OTP_TTL_SECONDS", "600"))  # code lifetime
STUDENT_OTP_MAX_ATTEMPTS = int(os.getenv("STUDENT_OTP_MAX_ATTEMPTS", "5"))  # verify tries per code
STUDENT_OTP_MAX_SENDS = int(os.getenv("STUDENT_OTP_MAX_SENDS", "3"))  # codes per window per id
STUDENT_OTP_SEND_WINDOW_SECONDS = int(os.getenv("STUDENT_OTP_SEND_WINDOW_SECONDS", "900"))
STUDENT_OTP_ASYNC_EMAIL = os.getenv("STUDENT_OTP_ASYNC_EMAIL", "true").lower() == "true"
# TESTING ONLY: send every student OTP to this address instead of the student's real
# university mailbox, so testing never emails an actual student. Leave EMPTY in production.
STUDENT_OTP_REDIRECT_EMAIL = os.getenv("STUDENT_OTP_REDIRECT_EMAIL", "").strip()
# TESTING ONLY: log a student in from the University ID alone, with NO code. This is a
# full authentication bypass — it requires BOTH DEBUG and this explicit opt-in, exactly
# like ALLOW_DEV_ROLE_SWITCH, and is inert in any production deployment (DEBUG=False).
STUDENT_LOGIN_NO_OTP = DEBUG and os.getenv("STUDENT_LOGIN_NO_OTP", "").lower() == "true"
# Behind a trusted reverse proxy (e.g. Render), derive the client IP from the
# right-most X-Forwarded-For entry (the one the proxy appended, unspoofable).
# Leave off for direct/dev, where REMOTE_ADDR is the real peer.
IP_FROM_XFF = os.getenv("IP_FROM_XFF", "false").lower() == "true"

# Optional Neo4j graph twin for timetable relationship analysis.
NEO4J_URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE", "neo4j")

# Portal credentials for scraper/runtime commands
PORTAL_ADMIN_USERNAME = os.getenv("PORTAL_ADMIN_USERNAME", "")
PORTAL_ADMIN_PASSWORD = os.getenv("PORTAL_ADMIN_PASSWORD", "")

# Backward-compatible aliases used by legacy modules
ADMIN_USERNAME = PORTAL_ADMIN_USERNAME
ADMIN_PASSWORD = PORTAL_ADMIN_PASSWORD

# Portal URLs (kept for compatibility with migrated/legacy scraper modules)
PORTAL_LOGIN_URL = "https://eas.taibahu.edu.sa/TaibahReg/teachers_login.jsp"
STUDENT_PLAN_URL = "https://eas.taibahu.edu.sa/TaibahReg/studentStudyPlanEnquiryEng.do?ex=preEx"
STUDENT_TIMETABLE_URL = "https://eas.taibahu.edu.sa/TaibahReg/studentSchedualEnquiry.do?ex=preEx"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", _("English")),
    ("ar", _("Arabic")),
]

# Where your translation files live:
#   <project_root>/locale/ar/LC_MESSAGES/django.po
#   <project_root>/locale/ar/LC_MESSAGES/django.mo
LOCALE_PATHS = [BASE_DIR / "locale"]

# Persist chosen language in a dedicated cookie (recommended to avoid clashes)
LANGUAGE_COOKIE_NAME = "advisor_language"
# Optional: keep cookie for 1 year
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365

# Use a real local timezone for staff-facing schedules/logs (recommended for KSA)
TIME_ZONE = "Asia/Riyadh"
USE_TZ = True

USE_I18N = True

# Django 5.x: USE_L10N is deprecated/removed; don't keep it.
# USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise: compressed + forever-cacheable static files in production
if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# ---------------------------------------------------------------------------
# Session security
# ---------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 28800  # 8 hours

if not DEBUG:
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ---------------------------------------------------------------------------
# CSRF security
# ---------------------------------------------------------------------------
CSRF_COOKIE_HTTPONLY = False  # Must be False — JS reads the cookie for X-CSRFToken headers
CSRF_COOKIE_SAMESITE = "Lax"

# ---------------------------------------------------------------------------
# Security headers (production only)
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # HTTPS enforcement
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Secure cookies over HTTPS only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# CSRF trusted origins (required for Django 4+ behind HTTPS reverse proxies)
_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# ---------------------------------------------------------------------------
# Authentication redirects
# ---------------------------------------------------------------------------
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },
    },
}


DATA_UPLOAD_MAX_MEMORY_SIZE = 10_485_760  # 10 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Timetable planner
# ---------------------------------------------------------------------------
# Multiplier applied to per-section demand when sizing rooms. 1.1 leaves a
# 10% buffer for late enrolments. Lowering toward 1.0 packs students tighter
# but risks overfilling when late adds arrive; raising above 1.1 wastes
# capacity. Override via env var TIMETABLE_CAPACITY_BUFFER.
TIMETABLE_CAPACITY_BUFFER = float(os.getenv("TIMETABLE_CAPACITY_BUFFER", "1.1"))

# PR2 commit 6 — typed room-failure reporting promoted to default.
# The room oracle returns refined ``RoomFailureReason`` records (NO_ROOM_TYPE,
# NO_ROOM_GENDER, NO_ROOM_CAPACITY, ROOM_OCCUPIED, ROOM_BUFFER_REJECT,
# ROOM_HEURISTIC_MISMATCH) instead of opaque UNASSIGNED strings. Flag is
# kept live so production can disable via env var if a regression appears.
TIMETABLE_PR2_ROOM_ORACLE_ENABLED = os.getenv(
    "TIMETABLE_PR2_ROOM_ORACLE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# PR3 commit 2 — decision-trace capture (explainability layer).
# When True (default from commit 2 onwards), ``auto_place_board`` will
# emit a ``DecisionTrace`` per placed section from commit 3, so
# downstream consumers can see the chosen slot + up to 3 rejected
# alternatives per placement. When False, the planner still emits
# ``decision_trace={}`` for schema stability so payload shape stays
# constant regardless of flag state. Observational only — no
# planning-decision change either way.
TIMETABLE_PR3_DECISION_TRACE_ENABLED = os.getenv(
    "TIMETABLE_PR3_DECISION_TRACE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# PR3 commit 5 — warm-start retention (minimal-perturbation layer).
# When True, ``auto_place_board`` accepts a ``baseline_placements`` map
# and retains legal baseline slots instead of re-scoring cold.
#
# Commit 8 (promotion): default flipped from ``False`` to ``True`` after
# the 10-fixture acceptance pack cleared the schema / coverage /
# zero-change / cold-start-parity / known-alphabet bars. The env var
# override is preserved as the kill-switch: set
# ``TIMETABLE_PR3_WARM_START_ENABLED=false`` to revert to cold-start
# behaviour without a redeploy. See ``docs/PR3-PROMOTION-NOTE.md``.
TIMETABLE_PR3_WARM_START_ENABLED = os.getenv(
    "TIMETABLE_PR3_WARM_START_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# ---------------------------------------------------------------------------
# PR4 — instructor realism + semantic cleanup (refactor/pr4-*)
# ---------------------------------------------------------------------------
#
# TIMETABLE_PR4_INSTRUCTOR_CLASH_ENABLED: gates real-time emission of the
# ``INSTRUCTOR_CLASH`` rejection code during candidate scoring. Promoted
# to ``True`` at commit 8. Env-overridable for the kill-switch path — set
# to ``false`` to revert to the pre-PR4 behaviour (no instructor-level
# rejection emitted) without a redeploy. See docs/PR4-PROMOTION-NOTE.md.
#
# TIMETABLE_LAB_HEURISTIC_UNIFIED: gates routing of planner / rooming /
# oracle through ``meeting_requires_lab_room()`` (commit 6's centralised
# predicate). Promoted to ``True`` at commit 8. ``False`` reverts each
# call-site to its old ``duration > 80`` literal (kill-switch path).
TIMETABLE_PR4_INSTRUCTOR_CLASH_ENABLED = os.getenv(
    "TIMETABLE_PR4_INSTRUCTOR_CLASH_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# When on, the planner's instructor-clash filter sources per-person identity
# from structured SectionInstructor links (true multi-instructor: a section's
# meeting clashes if ANY assigned instructor is double-booked) instead of the
# single opaque free-text name. Default ON as of 2026-07-16; set ``=false`` and
# the clash reads the free-text field exactly as before. Sections without links
# always fall back to the free-text path regardless of this flag.
TIMETABLE_INSTRUCTOR_LINKS_ENABLED = os.getenv(
    "TIMETABLE_INSTRUCTOR_LINKS_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_INSTRUCTOR_GAP_PENALTY_ENABLED: gates a soft objective that minimises
# idle time gaps in each instructor's daily schedule. When True, the canonical
# candidate evaluator appends a lowest-priority term (instructor idle minutes,
# strictly below every student + reserve term) and the greedy scorer prefers
# placements that compact an instructor's day. Requires per-section instructor
# identity, so it is meaningful only alongside TIMETABLE_INSTRUCTOR_LINKS_ENABLED.
# Default OFF — opt-in after a shadow run; with it off the score tuple is
# byte-identical to before. Env override ``=false`` is the live kill-switch.
TIMETABLE_INSTRUCTOR_GAP_PENALTY_ENABLED = os.getenv(
    "TIMETABLE_INSTRUCTOR_GAP_PENALTY_ENABLED", "false"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_INSTRUCTOR_DAILY_CAP_ENABLED: gates a HARD constraint capping the
# number of scheduled sessions (lectures AND labs both count) an instructor may
# teach on any single day at TIMETABLE_INSTRUCTOR_DAILY_CAP (default 3). A 4th
# same-day session is forbidden outright — the cap wins against students (a
# section may go unplaced rather than create an over-cap day). It is enforced
# STRUCTURALLY at candidate generation in every solver stage (greedy, V2
# local/chain, CP-SAT, SA), mirroring the instructor-clash filter, and is NEVER
# added to the lexicographic score tuple — so with it OFF the optimiser output is
# byte-identical to before. Meaningful only alongside TIMETABLE_INSTRUCTOR_LINKS_
# ENABLED (per-section instructor identity). Env override ``=false`` is the live
# kill-switch.
#
# DEFAULT ON since 2026-07-21: the registrar confirmed the 3/day limit is a hard
# rule an instructor must never break, and a build can always be arranged to
# honour it (an over-cap day is fixed by MOVING a session to a lighter day, not by
# dropping a class). Enabling was previously blocked by the repair pass's
# delete-bias — it dropped the 4th session instead of relocating it — now fixed,
# and the repair was hoisted to run whether or not the optimiser improved the
# student score. Compaction (below) stays OFF: it is a separate, still-room-blind
# pass.
TIMETABLE_INSTRUCTOR_DAILY_CAP_ENABLED = os.getenv(
    "TIMETABLE_INSTRUCTOR_DAILY_CAP_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")
TIMETABLE_INSTRUCTOR_DAILY_CAP = int(os.getenv("TIMETABLE_INSTRUCTOR_DAILY_CAP", "3"))

# TIMETABLE_INSTRUCTOR_COMPACTION_ENABLED: gates a post-build pass that compacts
# each instructor's day (shrinks within-day idle gaps) by relocating their
# sessions in TIME — never changing who teaches what. It runs AFTER the daily-cap
# repair and treats the cap as a hard gate. Strictly guarded: feasibility
# (unresolved/unassigned/clashes) and reserve never worsen; student schedule
# spread may rise only within a small budget, with tier-A + graduating students
# protected and a per-student ceiling; an unfavourable instructor/student trade
# is rejected. Default OFF — opt-in after scenario replays; meaningful only with
# TIMETABLE_INSTRUCTOR_LINKS_ENABLED. Env override ``=false`` is the kill-switch.
TIMETABLE_INSTRUCTOR_COMPACTION_ENABLED = os.getenv(
    "TIMETABLE_INSTRUCTOR_COMPACTION_ENABLED", "false"
).lower() in ("1", "true", "yes", "on")
# Tunables (env-overridable). Defaults match the validated scenario-627 replay.
TIMETABLE_INSTRUCTOR_COMPACTION_GAP_BUDGET = float(
    os.getenv("TIMETABLE_INSTRUCTOR_COMPACTION_GAP_BUDGET", "0.03")
)  # max fractional rise in TOTAL student gap-minutes
TIMETABLE_INSTRUCTOR_COMPACTION_PER_STUDENT_CAP = int(
    os.getenv("TIMETABLE_INSTRUCTOR_COMPACTION_PER_STUDENT_CAP", "75")
)  # max added gap minutes for any single student (~one slot/week)
TIMETABLE_INSTRUCTOR_COMPACTION_TRADE_RATIO = float(
    os.getenv("TIMETABLE_INSTRUCTOR_COMPACTION_TRADE_RATIO", "2.0")
)  # require >= this many instructor idle-min saved per student gap-min added
TIMETABLE_INSTRUCTOR_COMPACTION_MAX_ROUNDS = int(
    os.getenv("TIMETABLE_INSTRUCTOR_COMPACTION_MAX_ROUNDS", "40")
)
# Wall-clock budget (seconds) for the compaction search. It is worst-day-first,
# so the biggest idle wins land early; when the budget is hit it stops and
# persists what it found. Keeps a synchronous UI rebuild from overrunning the
# request thread. 0/negative disables the limit.
TIMETABLE_INSTRUCTOR_COMPACTION_TIME_BUDGET_SECONDS = float(
    os.getenv("TIMETABLE_INSTRUCTOR_COMPACTION_TIME_BUDGET_SECONDS", "20")
)

# TIMETABLE_TIERED_OBJECTIVE_ENABLED: gates the course-tier-aware lexicographic
# objective in the candidate evaluator. When True the evaluator returns a
# 9-element tuple that ranks resolution by course tier — Tier-1 (specialised
# major courses) is hard, Tier-2 (shared foundations, e.g. MATH/STAT/CS-service)
# tolerates a small unresolved count before turning near-hard, and Tier-3
# (ENGL/GS/GSE/FE gen-ed & free electives) is soft and never worsens student
# gaps. When False the score keeps its current 6-tuple shape and values, so
# optimiser output is byte-identical to before. Default OFF — opt-in after a
# shadow run. Env override ``=false`` is the live kill-switch.
# Default ON as of 2026-07-16: validated by shadow A/B across scn 620/625/632/635
# (core unresolved -> 0, clashes 69 -> 0, real gaps -13%..-32%) plus two rounds of
# multi-agent review. Set ``=false`` to fall back to the legacy flat objective —
# that path is byte-identical to pre-feature and the suite asserts it.
TIMETABLE_TIERED_OBJECTIVE_ENABLED = os.getenv(
    "TIMETABLE_TIERED_OBJECTIVE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")
# Per-Tier-2-course unresolved-seat tolerance: up to this many unresolved seats
# in a single Tier-2 course are "soft" (objective position E); the excess is
# "near-hard" (position C). Default 3. Read via get_tiered_t2_tolerance(), which
# floors it at 0.
TIMETABLE_TIERED_T2_TOLERANCE = int(os.getenv("TIMETABLE_TIERED_T2_TOLERANCE", "3"))
# Bounded trade: gap-minutes a single soft-tier unresolved seat is "worth". The
# tiered student-cost position is real_gap + this * soft_unresolved, so the
# optimiser seats a gen-ed/elective (soft) course when it adds fewer than this
# many gap-minutes and declines when it costs more. Default 120 (~two class
# slots). 0 = strict quality-first (gaps always beat gen-ed).
TIMETABLE_TIERED_SOFT_GAP_BUDGET = int(os.getenv("TIMETABLE_TIERED_SOFT_GAP_BUDGET", "120"))

# TIMETABLE_ONLINE_GAP_EXCLUSION_ENABLED: exclude ONLINE sessions from the
# student and instructor gap chains. An online class is attended remotely, so the
# minutes around it are not on-campus idle time — charging them overstates
# gap_minutes for every student holding an online course and can make the
# optimiser pay real on-campus quality (or move an in-person class "next to" an
# online one) to close a gap that does not exist. Correctness fix, so DEFAULT ON;
# ``=false`` restores the previous online-blind scoring, which is byte-identical
# because with the flag off no SectionState is ever marked online.
TIMETABLE_ONLINE_GAP_EXCLUSION_ENABLED = os.getenv(
    "TIMETABLE_ONLINE_GAP_EXCLUSION_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

TIMETABLE_LAB_HEURISTIC_UNIFIED = os.getenv("TIMETABLE_LAB_HEURISTIC_UNIFIED", "true").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# ---------------------------------------------------------------------------
# PR5 — solver-pipeline decision-trace parity (refactor/pr5-*)
# ---------------------------------------------------------------------------
#
# TIMETABLE_PR5_STAGE_TRACE_ENABLED: single flag gating all PR5 trace
# surface additions — ``stage_origin`` population on ``DecisionTrace``,
# emission of SA_RELOCATE_ACCEPTED / CPSAT_IMPROVED / CHAIN_ROTATED /
# ROOMING_REPAIR_REASSIGNED codes, and ``perturbation_metric.changes_by_stage``.
# Default ``false`` in commits 2-7 (new surface stays off during
# development); commit 8 flips the env default to ``true`` (the
# promotion commit). See docs/PR5-DOR.md flag plan and
# docs/PR5-PROMOTION-NOTE.md (lands at commit 8) for rollback.
TIMETABLE_PR5_STAGE_TRACE_ENABLED = os.getenv(
    "TIMETABLE_PR5_STAGE_TRACE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# ---------------------------------------------------------------------------
# PR6 — stage-telemetry (refactor/pr6-stage-telemetry)
# ---------------------------------------------------------------------------
#
# TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED: single flag gating PR6 observability-
# only stage-telemetry population. When True, callers write real values into
# ``result['stage_telemetry']['stage_ms']`` and ``stage_iterations`` for the
# five V2 pipeline stages (greedy, sa, cpsat, chain, rooming_repair). When
# False, the block is still present on every result (schema-stable) but every
# value stays at 0. Default flipped to ``true`` at commit 8 (promotion). Env
# override ``TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED=false`` reverts to zeroed
# telemetry at runtime — no redeploy. See docs/PR6-DOR.md flag plan and
# docs/PR6-PROMOTION-NOTE.md for rollback tiers.
TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED = os.getenv(
    "TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_PR7_ASYNC_PLANNER_ENABLED: single flag gating PR7 async-planner
# execution path. When True, POST /planner-jobs/ dispatches the run on a
# single-worker ThreadPoolExecutor and returns 201 immediately; poll /result/
# surface the PlannerJob audit row. When False, all four /planner-jobs/*
# endpoints 404 and no PlannerJob row is created — pre-PR7 behaviour is
# byte-identical. Default flipped to ``true`` at commit 8 (promotion). Env
# override ``TIMETABLE_PR7_ASYNC_PLANNER_ENABLED=false`` reverts the shim at
# runtime — no redeploy. See docs/PR7-DOR.md flag plan and
# docs/PR7-PROMOTION-NOTE.md for rollback tiers.
TIMETABLE_PR7_ASYNC_PLANNER_ENABLED = os.getenv(
    "TIMETABLE_PR7_ASYNC_PLANNER_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# Planner jobs are process-local (not durable across restarts), so a server
# stop/reap can leave a PlannerJob stranded in RUNNING forever. A job still
# RUNNING (or QUEUED-but-never-dispatched) past this many minutes is treated as
# orphaned and reconciled to FAILED — on submit, on poll, and via the
# ``reconcile_planner_jobs`` management command. Generous default so a genuinely
# long build is never swept by mistake.
TIMETABLE_PLANNER_JOB_STALE_MINUTES = int(os.getenv("TIMETABLE_PLANNER_JOB_STALE_MINUTES", "45"))

# TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED: single flag gating the PR8 async-job
# UX card on the Timetable Workspace page. When True, renders a status
# card with pill/submit/cancel/view-result/rerun controls that drives the
# PR7 job endpoints. When False, no card renders — byte parity with
# pre-PR8 scenario page. Default flipped to ``true`` at commit 8
# (promotion). Env override ``TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED=false``
# hides the card at runtime with no redeploy. See docs/PR8-DOR.md flag
# plan and docs/PR8-PROMOTION-NOTE.md for rollback tiers.
TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED = os.getenv(
    "TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_ENFORCE_LOCKS: enforce registrar placement locks across every
# planner stage. When True, locked SectionPlacement rows are preserved through
# greedy auto-place, per-board CP-SAT, the global polisher, load-balanced and
# simulated annealing (and their persist paths) — a locked cell is never
# relocated, re-roomed, or deleted on a re-solve. When False, locks are
# advisory only (pre-refactor behaviour). Env override
# ``TIMETABLE_ENFORCE_LOCKS=false`` disables enforcement at runtime — no
# redeploy. Default ``true``: the workspace exposes a lock toggle, so the
# planner must honour it. Latent until rows are actually locked.
TIMETABLE_ENFORCE_LOCKS = os.getenv("TIMETABLE_ENFORCE_LOCKS", "true").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# ── V2 full-rebuild chain-search budget (OPT-IN speed/quality lever) ──────────
# The post-greedy chain search re-evaluates the full student objective per move
# with no natural cheap bound, so on large multi-board scenarios it dominates
# the runtime (measured ~471s of an ~874s full rebuild). It is, however,
# PRODUCTIVE work: a measured 60s cap cut the rebuild to ~447s but left 14
# unresolved students versus 1 with the chain run in full — so a blunt cap
# trades student-assignment quality for speed.
#
# Therefore this budget defaults to 0 = UNBOUNDED (full quality preserved). It
# is an opt-in operator lever: set e.g. TIMETABLE_CHAIN_TIME_LIMIT_SECONDS=60 to
# bound the chain stage when faster turnaround matters more than the last few
# unresolved students. The stop is safe by construction — chain_local_search
# only ever advances current_best to a strictly-improving, fully re-evaluated
# board, so an early stop returns the best-so-far, never a worse board than the
# chain started from. (0 / negative / unset ⇒ no deadline.)
TIMETABLE_CHAIN_TIME_LIMIT_SECONDS = float(os.getenv("TIMETABLE_CHAIN_TIME_LIMIT_SECONDS", "0"))

# Per-board solver budget used *inside* V2 candidate generation only (the
# optimal / adaptive / hybrid / load_balanced strategies). On realistic
# multi-board scenarios these heavy strategies produce candidates equivalent to
# plain compact (measured: 6 of 7 strategies tied, a greedy strategy won), yet
# their CP-SAT/SA solves burn ~150s. Since candidates are only RANKED — the
# winner is re-placed and fully polished afterwards — a tight budget here saves
# wall-clock with no effect on the final board. Scoped to the sweep: standalone
# auto_place_scenario callers are unaffected. Set to 0 to disable (full
# per-strategy budgets, pre-change behaviour).
TIMETABLE_CANDIDATE_GEN_BUDGET_SECONDS = float(
    os.getenv("TIMETABLE_CANDIDATE_GEN_BUDGET_SECONDS", "1.5")
)
