"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from project root .env if present
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.getenv("DJANGO_SECRET_KEY", "")
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    # Allow insecure fallback ONLY in local development (DEBUG=True)
    SECRET_KEY = "django-insecure-dev-only-change-me"  # noqa: S105
else:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY environment variable is required when DEBUG is False."
    )

ALLOWED_HOSTS: list[str] = [
    h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "whatsapp_gateway",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Must be after SessionMiddleware and before CommonMiddleware.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# In production, set DATABASE_URL (e.g. postgres://user:pass@host:5432/dbname).
# Locally falls back to SQLite.

_database_url = os.getenv("DATABASE_URL")
if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
            "OPTIONS": {
                "timeout": 30,
            },
        }
    }

# Cache backend for rate limiting and login throttling
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "advisor-cache",
    }
}

# Legacy parity DB used by migrated advisor logic (can be overridden via env var)
DB_PATH = os.getenv("ADVISOR_DB_PATH", str(BASE_DIR / "db.sqlite3"))

# Local-only OpenAI-compatible LLM endpoint.  LM Studio defaults to this port.
LOCAL_LLM_BASE_URL = os.getenv("LOCAL_LLM_BASE_URL", "http://localhost:1234/v1")
LOCAL_LLM_MODEL = os.getenv("LOCAL_LLM_MODEL", "")
LOCAL_LLM_TIMEOUT_SECONDS = float(os.getenv("LOCAL_LLM_TIMEOUT_SECONDS", "120"))
LOCAL_LLM_MAX_TOKENS = int(os.getenv("LOCAL_LLM_MAX_TOKENS", "1400"))
LOCAL_LLM_ALLOW_REMOTE = os.getenv("LOCAL_LLM_ALLOW_REMOTE", "false").lower() == "true"

# Virtual advisor agent loop (native LLM tool calling over the capability
# registry). Env-overridable kill-switch: set to "false" to revert to the
# single-shot regex-planned behaviour with no redeploy.
VIRTUAL_ADVISOR_AGENT_LOOP_ENABLED = (
    os.getenv("VIRTUAL_ADVISOR_AGENT_LOOP_ENABLED", "true").lower() == "true"
)
VIRTUAL_ADVISOR_MAX_TOOL_ITERATIONS = int(os.getenv("VIRTUAL_ADVISOR_MAX_TOOL_ITERATIONS", "5"))
VIRTUAL_ADVISOR_MAX_TOOL_CALLS = int(os.getenv("VIRTUAL_ADVISOR_MAX_TOOL_CALLS", "12"))
# Token budget for tool-enabled turns. Thinking models (Qwen reasoning
# variants) burn output tokens on hidden reasoning before tool calls or
# answers, so loop turns need more headroom than plain chat turns.
VIRTUAL_ADVISOR_LOOP_MAX_TOKENS = int(os.getenv("VIRTUAL_ADVISOR_LOOP_MAX_TOKENS", "3000"))
# Per-turn HTTP timeout for tool-enabled turns. Thinking models can stall
# a tool turn for the full LOCAL_LLM_TIMEOUT_SECONDS; a shorter per-turn
# limit hands control to the fast no-tools rescue path sooner.
VIRTUAL_ADVISOR_TOOL_TURN_TIMEOUT_SECONDS = float(
    os.getenv("VIRTUAL_ADVISOR_TOOL_TURN_TIMEOUT_SECONDS", "75")
)

# WhatsApp Advisor Gateway. Keep credentials out of the repository.
WHATSAPP_CLOUD_API_VERSION = os.getenv("WHATSAPP_CLOUD_API_VERSION", "v23.0")
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN", "")
WHATSAPP_APP_SECRET = os.getenv("WHATSAPP_APP_SECRET", "")
WHATSAPP_REQUIRE_SIGNATURE = (
    os.getenv("WHATSAPP_REQUIRE_SIGNATURE", "false" if DEBUG else "true").lower() == "true"
)
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_STUDENT_EMAIL_DOMAIN = os.getenv("WHATSAPP_STUDENT_EMAIL_DOMAIN", "")
WHATSAPP_OTP_TTL_SECONDS = int(os.getenv("WHATSAPP_OTP_TTL_SECONDS", "300"))
WHATSAPP_OTP_MAX_ATTEMPTS = int(os.getenv("WHATSAPP_OTP_MAX_ATTEMPTS", "5"))
WHATSAPP_ALLOW_SUPER_ADMIN = os.getenv("WHATSAPP_ALLOW_SUPER_ADMIN", "false").lower() == "true"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "advisor-bot@localhost")

# Optional Neo4j graph twin for timetable relationship analysis.
NEO4J_URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE", "neo4j")

# Portal credentials for scraper/runtime commands
PORTAL_ADMIN_USERNAME = os.getenv("PORTAL_ADMIN_USERNAME", "")
PORTAL_ADMIN_PASSWORD = os.getenv("PORTAL_ADMIN_PASSWORD", "")

# Backward-compatible aliases used by legacy modules
ADMIN_USERNAME = PORTAL_ADMIN_USERNAME
ADMIN_PASSWORD = PORTAL_ADMIN_PASSWORD

# Portal URLs (kept for compatibility with migrated/legacy scraper modules)
PORTAL_LOGIN_URL = "https://eas.taibahu.edu.sa/TaibahReg/teachers_login.jsp"
STUDENT_PLAN_URL = "https://eas.taibahu.edu.sa/TaibahReg/studentStudyPlanEnquiryEng.do?ex=preEx"
STUDENT_TIMETABLE_URL = "https://eas.taibahu.edu.sa/TaibahReg/studentSchedualEnquiry.do?ex=preEx"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", _("English")),
    ("ar", _("Arabic")),
]

# Where your translation files live:
#   <project_root>/locale/ar/LC_MESSAGES/django.po
#   <project_root>/locale/ar/LC_MESSAGES/django.mo
LOCALE_PATHS = [BASE_DIR / "locale"]

# Persist chosen language in a dedicated cookie (recommended to avoid clashes)
LANGUAGE_COOKIE_NAME = "advisor_language"
# Optional: keep cookie for 1 year
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365

# Use a real local timezone for staff-facing schedules/logs (recommended for KSA)
TIME_ZONE = "Asia/Riyadh"
USE_TZ = True

USE_I18N = True

# Django 5.x: USE_L10N is deprecated/removed; don't keep it.
# USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise: compressed + forever-cacheable static files in production
if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# ---------------------------------------------------------------------------
# Session security
# ---------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 28800  # 8 hours

if not DEBUG:
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ---------------------------------------------------------------------------
# CSRF security
# ---------------------------------------------------------------------------
CSRF_COOKIE_HTTPONLY = False  # Must be False — JS reads the cookie for X-CSRFToken headers
CSRF_COOKIE_SAMESITE = "Lax"

# ---------------------------------------------------------------------------
# Security headers (production only)
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # HTTPS enforcement
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Secure cookies over HTTPS only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# CSRF trusted origins (required for Django 4+ behind HTTPS reverse proxies)
_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# ---------------------------------------------------------------------------
# Authentication redirects
# ---------------------------------------------------------------------------
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO" if DEBUG else "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },
    },
}


DATA_UPLOAD_MAX_MEMORY_SIZE = 10_485_760  # 10 MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Timetable planner
# ---------------------------------------------------------------------------
# Multiplier applied to per-section demand when sizing rooms. 1.1 leaves a
# 10% buffer for late enrolments. Lowering toward 1.0 packs students tighter
# but risks overfilling when late adds arrive; raising above 1.1 wastes
# capacity. Override via env var TIMETABLE_CAPACITY_BUFFER.
TIMETABLE_CAPACITY_BUFFER = float(os.getenv("TIMETABLE_CAPACITY_BUFFER", "1.1"))

# PR2 commit 6 — typed room-failure reporting promoted to default.
# The room oracle returns refined ``RoomFailureReason`` records (NO_ROOM_TYPE,
# NO_ROOM_GENDER, NO_ROOM_CAPACITY, ROOM_OCCUPIED, ROOM_BUFFER_REJECT,
# ROOM_HEURISTIC_MISMATCH) instead of opaque UNASSIGNED strings. Flag is
# kept live so production can disable via env var if a regression appears.
TIMETABLE_PR2_ROOM_ORACLE_ENABLED = os.getenv(
    "TIMETABLE_PR2_ROOM_ORACLE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# PR3 commit 2 — decision-trace capture (explainability layer).
# When True (default from commit 2 onwards), ``auto_place_board`` will
# emit a ``DecisionTrace`` per placed section from commit 3, so
# downstream consumers can see the chosen slot + up to 3 rejected
# alternatives per placement. When False, the planner still emits
# ``decision_trace={}`` for schema stability so payload shape stays
# constant regardless of flag state. Observational only — no
# planning-decision change either way.
TIMETABLE_PR3_DECISION_TRACE_ENABLED = os.getenv(
    "TIMETABLE_PR3_DECISION_TRACE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# PR3 commit 5 — warm-start retention (minimal-perturbation layer).
# When True, ``auto_place_board`` accepts a ``baseline_placements`` map
# and retains legal baseline slots instead of re-scoring cold.
#
# Commit 8 (promotion): default flipped from ``False`` to ``True`` after
# the 10-fixture acceptance pack cleared the schema / coverage /
# zero-change / cold-start-parity / known-alphabet bars. The env var
# override is preserved as the kill-switch: set
# ``TIMETABLE_PR3_WARM_START_ENABLED=false`` to revert to cold-start
# behaviour without a redeploy. See ``docs/PR3-PROMOTION-NOTE.md``.
TIMETABLE_PR3_WARM_START_ENABLED = os.getenv(
    "TIMETABLE_PR3_WARM_START_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# ---------------------------------------------------------------------------
# PR4 — instructor realism + semantic cleanup (refactor/pr4-*)
# ---------------------------------------------------------------------------
#
# TIMETABLE_PR4_INSTRUCTOR_CLASH_ENABLED: gates real-time emission of the
# ``INSTRUCTOR_CLASH`` rejection code during candidate scoring. Promoted
# to ``True`` at commit 8. Env-overridable for the kill-switch path — set
# to ``false`` to revert to the pre-PR4 behaviour (no instructor-level
# rejection emitted) without a redeploy. See docs/PR4-PROMOTION-NOTE.md.
#
# TIMETABLE_LAB_HEURISTIC_UNIFIED: gates routing of planner / rooming /
# oracle through ``meeting_requires_lab_room()`` (commit 6's centralised
# predicate). Promoted to ``True`` at commit 8. ``False`` reverts each
# call-site to its old ``duration > 80`` literal (kill-switch path).
TIMETABLE_PR4_INSTRUCTOR_CLASH_ENABLED = os.getenv(
    "TIMETABLE_PR4_INSTRUCTOR_CLASH_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

TIMETABLE_LAB_HEURISTIC_UNIFIED = os.getenv("TIMETABLE_LAB_HEURISTIC_UNIFIED", "true").lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# ---------------------------------------------------------------------------
# PR5 — solver-pipeline decision-trace parity (refactor/pr5-*)
# ---------------------------------------------------------------------------
#
# TIMETABLE_PR5_STAGE_TRACE_ENABLED: single flag gating all PR5 trace
# surface additions — ``stage_origin`` population on ``DecisionTrace``,
# emission of SA_RELOCATE_ACCEPTED / CPSAT_IMPROVED / CHAIN_ROTATED /
# ROOMING_REPAIR_REASSIGNED codes, and ``perturbation_metric.changes_by_stage``.
# Default ``false`` in commits 2-7 (new surface stays off during
# development); commit 8 flips the env default to ``true`` (the
# promotion commit). See docs/PR5-DOR.md flag plan and
# docs/PR5-PROMOTION-NOTE.md (lands at commit 8) for rollback.
TIMETABLE_PR5_STAGE_TRACE_ENABLED = os.getenv(
    "TIMETABLE_PR5_STAGE_TRACE_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# ---------------------------------------------------------------------------
# PR6 — stage-telemetry (refactor/pr6-stage-telemetry)
# ---------------------------------------------------------------------------
#
# TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED: single flag gating PR6 observability-
# only stage-telemetry population. When True, callers write real values into
# ``result['stage_telemetry']['stage_ms']`` and ``stage_iterations`` for the
# five V2 pipeline stages (greedy, sa, cpsat, chain, rooming_repair). When
# False, the block is still present on every result (schema-stable) but every
# value stays at 0. Default flipped to ``true`` at commit 8 (promotion). Env
# override ``TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED=false`` reverts to zeroed
# telemetry at runtime — no redeploy. See docs/PR6-DOR.md flag plan and
# docs/PR6-PROMOTION-NOTE.md for rollback tiers.
TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED = os.getenv(
    "TIMETABLE_PR6_STAGE_TELEMETRY_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_PR7_ASYNC_PLANNER_ENABLED: single flag gating PR7 async-planner
# execution path. When True, POST /planner-jobs/ dispatches the run on a
# single-worker ThreadPoolExecutor and returns 201 immediately; poll /result/
# surface the PlannerJob audit row. When False, all four /planner-jobs/*
# endpoints 404 and no PlannerJob row is created — pre-PR7 behaviour is
# byte-identical. Default flipped to ``true`` at commit 8 (promotion). Env
# override ``TIMETABLE_PR7_ASYNC_PLANNER_ENABLED=false`` reverts the shim at
# runtime — no redeploy. See docs/PR7-DOR.md flag plan and
# docs/PR7-PROMOTION-NOTE.md for rollback tiers.
TIMETABLE_PR7_ASYNC_PLANNER_ENABLED = os.getenv(
    "TIMETABLE_PR7_ASYNC_PLANNER_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED: single flag gating the PR8 async-job
# UX card on the Timetable Workspace page. When True, renders a status
# card with pill/submit/cancel/view-result/rerun controls that drives the
# PR7 job endpoints. When False, no card renders — byte parity with
# pre-PR8 scenario page. Default flipped to ``true`` at commit 8
# (promotion). Env override ``TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED=false``
# hides the card at runtime with no redeploy. See docs/PR8-DOR.md flag
# plan and docs/PR8-PROMOTION-NOTE.md for rollback tiers.
TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED = os.getenv(
    "TIMETABLE_PR8_ASYNC_JOB_UI_ENABLED", "true"
).lower() in ("1", "true", "yes", "on")

# TIMETABLE_ENFORCE_LOCKS: enforce registrar placement locks across every
# planner stage. When True, locked SectionPlacement rows are preserved through
# greedy auto-place, per-board CP-SAT, the global polisher, load-balanced and
# simulated annealing (and their persist paths) — a locked cell is never
# relocated, re-roomed, or deleted on a re-solve. When False, locks are
# advisory only (pre-refactor behaviour). Env override
# ``TIMETABLE_ENFORCE_LOCKS=false`` disables enforcement at runtime — no
# redeploy. Default ``true``: the workspace exposes a lock toggle, so the
# planner must honour it. Latent until rows are actually locked.
TIMETABLE_ENFORCE_LOCKS = os.getenv("TIMETABLE_ENFORCE_LOCKS", "true").lower() in (
    "1",
    "true",
    "yes",
    "on",
)
