# Generated by Django 5.2.11 on 2026-05-14 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0025_planner_course_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_id", models.TextField(unique=True)),
                ("state", models.TextField(blank=True, default="")),
                ("last_auth_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("step_up_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "whatsapp_conversations",
                "indexes": [
                    models.Index(fields=["wa_id"], name="idx_wc_wa_id"),
                    models.Index(fields=["state"], name="idx_wc_state"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_id", models.TextField()),
                ("direction", models.TextField()),
                ("message_type", models.TextField(blank=True, default="")),
                ("text_preview", models.TextField(blank=True, default="")),
                ("status", models.TextField(blank=True, default="")),
                ("provider_message_id", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "whatsapp_message_logs",
                "indexes": [
                    models.Index(fields=["wa_id"], name="idx_wml_wa_id"),
                    models.Index(fields=["direction"], name="idx_wml_direction"),
                    models.Index(fields=["created_at"], name="idx_wml_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppOtpChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_id", models.TextField()),
                ("phone_number", models.TextField(blank=True, default="")),
                ("university_id", models.TextField()),
                ("resolved_role", models.TextField()),
                ("resolved_advisor_id", models.TextField(blank=True, default="")),
                ("resolved_departments", models.TextField(blank=True, default="")),
                ("email_masked", models.TextField(blank=True, default="")),
                ("otp_hash", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("status", models.TextField(default="pending")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.student",
                    ),
                ),
                (
                    "resolved_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_otp_challenges",
                "indexes": [
                    models.Index(fields=["wa_id", "status"], name="idx_woc_wa_status"),
                    models.Index(
                        fields=["university_id"], name="idx_woc_university_id"
                    ),
                    models.Index(fields=["expires_at"], name="idx_woc_expires"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wa_id", models.TextField(unique=True)),
                ("phone_number", models.TextField(blank=True, default="")),
                ("role", models.TextField()),
                ("status", models.TextField(default="active")),
                ("advisor_id", models.TextField(blank=True, default="")),
                ("departments", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_user_links",
                "indexes": [
                    models.Index(fields=["wa_id"], name="idx_wal_wa_id"),
                    models.Index(fields=["role", "status"], name="idx_wal_role_status"),
                    models.Index(fields=["student"], name="idx_wal_student"),
                    models.Index(fields=["advisor_id"], name="idx_wal_advisor"),
                ],
            },
        ),
    ]
