# Generated by Django 5.2.16 on 2026-08-10 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0061_scope_student_term_section_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLinkToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("telegram_user_id", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_student_id", models.IntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirm_code_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("confirm_attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "telegram_link_tokens",
            },
        ),
        migrations.CreateModel(
            name="TelegramUpdateReceipt",
            fields=[
                (
                    "update_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "telegram_update_receipts",
            },
        ),
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(db_index=True)),
                ("student_id", models.IntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_links",
                        to="core.advisorconversation",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_links",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("telegram_user_id",),
                        name="uq_tg_active_telegram_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("student_id",),
                        name="uq_tg_active_student",
                    ),
                ],
            },
        ),
    ]
