# Generated by Django 5.2.16 on 2026-08-11 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models.functions import Now


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_scope_student_term_section_uniqueness"),
        ("telegram_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="assistant_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_update_jobs",
                to="core.advisormessage",
            ),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="available_at",
            field=models.DateTimeField(
                db_default=Now(), default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_update_jobs",
                to="core.advisorconversation",
            ),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="delivery_cursor",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="delivery_payload",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="error_code",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INLINE", "Inline receipt"),
                    ("QUESTION", "Advisor question"),
                    ("COMMAND", "Ordered command"),
                ],
                db_default="INLINE",
                default="INLINE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="update_jobs",
                to="telegram_gateway.telegramlink",
            ),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="locked_by",
            field=models.CharField(blank=True, db_default="", default="", max_length=128),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="payload_text",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="result_code",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AddField(
            model_name="telegramupdatereceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_default="SUCCEEDED",
                default="SUCCEEDED",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="telegramupdatereceipt",
            index=models.Index(
                fields=["status", "available_at", "update_id"], name="idx_tg_job_ready"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramupdatereceipt",
            index=models.Index(
                fields=["link", "status", "update_id"], name="idx_tg_job_link_fifo"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramupdatereceipt",
            index=models.Index(
                fields=["status", "lease_expires_at"], name="idx_tg_job_lease"
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramupdatereceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("link__isnull", False), ("status", "RUNNING")),
                fields=("link",),
                name="uq_tg_running_link",
            ),
        ),
    ]
