# Generated by Django 5.2.16 on 2026-07-27 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchedulerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.TextField()),
                ("term", models.IntegerField()),
                ("gender", models.TextField()),
                (
                    "programs",
                    models.TextField(help_text="comma-separated, as requested"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.TextField(blank=True, default="")),
                ("snapshot_fingerprint", models.TextField()),
                ("rulebook_fingerprint", models.TextField()),
                ("config_fingerprint", models.TextField()),
                ("config", models.JSONField(default=dict)),
                ("solver_status", models.TextField()),
                ("wall_time_seconds", models.FloatField(default=0.0)),
                ("violation_count", models.IntegerField(default=0)),
                ("certification", models.TextField(default="UNCERTIFIED")),
                (
                    "expected_clashes",
                    models.FloatField(
                        default=0.0,
                        help_text="the optimised PROXY, not a student outcome",
                    ),
                ),
                ("naive_baseline", models.FloatField(default=0.0)),
                ("instructor_days", models.IntegerField(default=0)),
                (
                    "instructor_days_floor",
                    models.IntegerField(
                        default=0,
                        help_text="proven minimum; equal means it cannot be improved",
                    ),
                ),
                ("instructor_idle_minutes", models.IntegerField(default=0)),
                ("sections_assigned", models.IntegerField(default=0)),
                (
                    "sections_staffable",
                    models.IntegerField(
                        default=0,
                        help_text="only the department's own courses are ever staffed",
                    ),
                ),
                ("unroomed", models.IntegerField(default=0)),
                (
                    "unroomed_floor",
                    models.IntegerField(
                        default=0,
                        help_text="impossible + saturated; no timetable can beat this",
                    ),
                ),
                ("sibling_pairs_back_to_back", models.IntegerField(default=0)),
                ("sibling_pairs_achievable", models.IntegerField(default=0)),
                ("students_seated", models.IntegerField(blank=True, null=True)),
                (
                    "students_clash_free_percent",
                    models.FloatField(blank=True, null=True),
                ),
                ("student_idle_minutes_avg", models.FloatField(blank=True, null=True)),
                ("notes", models.JSONField(default=list)),
            ],
            options={
                "db_table": "sch_plan",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["academic_year", "term", "gender"],
                        name="sch_plan_academi_aa3af7_idx",
                    ),
                    models.Index(
                        fields=["snapshot_fingerprint"],
                        name="sch_plan_snapsho_122d6c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchedulerPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.TextField()),
                ("offering_id", models.TextField()),
                ("course_code", models.TextField()),
                ("section_label", models.TextField()),
                ("meeting_index", models.IntegerField()),
                ("kind", models.TextField()),
                ("delivery", models.TextField()),
                ("day", models.TextField()),
                ("start_minute", models.IntegerField()),
                ("end_minute", models.IntegerField()),
                ("room_id", models.TextField(blank=True, default="")),
                ("instructor_id", models.IntegerField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="scheduler.schedulerplan",
                    ),
                ),
            ],
            options={
                "db_table": "sch_placement",
                "ordering": ["day", "start_minute", "course_code"],
                "indexes": [
                    models.Index(
                        fields=["plan", "day"], name="sch_placeme_plan_id_4f7552_idx"
                    ),
                    models.Index(
                        fields=["plan", "instructor_id"],
                        name="sch_placeme_plan_id_e964ed_idx",
                    ),
                ],
            },
        ),
    ]
