# Generated by Django 5.2.16 on 2026-07-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerplan",
            name="sections_same_hour_percent",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="schedulerplan",
            name="sections_within_one_slot_percent",
            field=models.FloatField(default=0.0),
        ),
    ]
